version: '3.9'
services:
  geth:
    build: .
    container_name: geth
    command: >
      --networkid ${NETWORK_ID}
      --bootnodes=${ENODE}
      --http.api "clique,personal,eth,net,web3,miner,admin"
      --http.corsdomain="*"
      --http
      --http.addr="0.0.0.0"
      --http.port=8545
      --snapshot=false
      --syncmode="full"
      --nodiscover
      --datadir=/root/.ethereum
      --unlock=${ACCOUNT_ADDR}
      --password=/root/.ethereum/passwd
      --allow-insecure-unlock
      --nat extip:${EXTIP}
    ports:
      - 8545:8545
      - 30303:30303
    volumes:
      - ./volume/.ethereum:/root/.ethereum
